create table if not exists public.question_groups (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  image_path text,
  sort_order integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.question_groups add column if not exists image_path text;

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  content text not null,
  description text not null default '',
  question_group_id bigint not null references public.question_groups(id),
  sort_order integer not null default 1,
  is_active boolean not null default true,
  in_use boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.questions add column if not exists description text not null default '';

create table if not exists public.book_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  cover_image text,
  cover_color text not null default '#00BC3C',
  text_color text not null default '#FFFFFF',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.book_types add column if not exists cover_color text not null default '#00BC3C';
alter table public.book_types add column if not exists text_color text not null default '#FFFFFF';
alter table public.book_types add column if not exists sort_order integer not null default 1;
alter table public.book_types alter column cover_color set default '#00BC3C';
alter table public.book_types alter column text_color set default '#FFFFFF';

create table if not exists public.question_book_types (
  question_id bigint not null references public.questions(id) on delete cascade,
  book_type_id bigint not null references public.book_types(id) on delete cascade,
  primary key (question_id, book_type_id)
);

create index if not exists question_book_types_question_id_idx on public.question_book_types(question_id);
create index if not exists question_book_types_book_type_id_idx on public.question_book_types(book_type_id);

update public.book_types
set sort_order = case
  when lower(name) like '%single parent%' or name like '%한부모%' then 2
  when lower(name) like '%single%' or name like '%싱글%' then 3
  when lower(name) like '%couple%' or name like '%커플%' or name like '%부부%' then 4
  when lower(name) like '%parent%' or name like '%부모%' then 1
  else coalesce(sort_order, id)
end
where sort_order = 1;

create table if not exists public.book_type_question_groups (
  book_type_id bigint not null references public.book_types(id) on delete cascade,
  question_group_id bigint not null references public.question_groups(id),
  primary key (book_type_id, question_group_id)
);

create table if not exists public.my_books (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id),
  book_type_id bigint not null references public.book_types(id),
  title text not null,
  sender text,
  receiver text,
  introduction text,
  status text not null default 'writing' check (status in ('writing', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

alter table public.my_books add column if not exists owner_id uuid references auth.users(id);
create index if not exists my_books_owner_id_idx on public.my_books(owner_id);

create table if not exists public.my_book_answers (
  id bigint generated by default as identity primary key,
  my_book_id bigint not null references public.my_books(id) on delete cascade,
  question_id bigint not null references public.questions(id),
  answer text not null default '',
  is_final boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (my_book_id, question_id)
);

create table if not exists public.publications (
  id bigint generated by default as identity primary key,
  my_book_id bigint not null references public.my_books(id) on delete cascade,
  cover_style text not null default 'classic',
  cover_color text,
  cover_image text,
  created_at timestamptz not null default now()
);

alter table public.publications add column if not exists cover_color text;
alter table public.publications add column if not exists cover_image text;

create table if not exists public.cover_colors (
  id bigint generated by default as identity primary key,
  name text not null,
  color_value text not null check (color_value ~ '^#[0-9A-Fa-f]{6}$'),
  sort_order integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cover_images (
  id bigint generated by default as identity primary key,
  name text not null,
  image_path text not null,
  image_column integer not null default 1 check (image_column in (1, 2)),
  sort_order integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cover_colors add column if not exists name text;
alter table public.cover_colors add column if not exists color_value text;
alter table public.cover_colors add column if not exists sort_order integer not null default 1;
alter table public.cover_colors add column if not exists is_active boolean not null default true;
alter table public.cover_colors add column if not exists created_at timestamptz not null default now();
alter table public.cover_colors add column if not exists updated_at timestamptz not null default now();
alter table public.cover_images add column if not exists name text;
alter table public.cover_images add column if not exists image_path text;
alter table public.cover_images add column if not exists image_column integer not null default 1;
alter table public.cover_images add column if not exists sort_order integer not null default 1;
alter table public.cover_images add column if not exists is_active boolean not null default true;
alter table public.cover_images add column if not exists created_at timestamptz not null default now();
alter table public.cover_images add column if not exists updated_at timestamptz not null default now();

create index if not exists cover_colors_active_order_idx on public.cover_colors(is_active, sort_order);
create index if not exists cover_images_active_column_order_idx on public.cover_images(is_active, image_column, sort_order);
create unique index if not exists cover_colors_name_value_uidx on public.cover_colors(name, color_value);
create unique index if not exists cover_images_name_path_column_uidx on public.cover_images(name, image_path, image_column);

insert into public.cover_colors (name, color_value, sort_order) values
  ('Cream', '#C5A58E', 1), ('Rose', '#D9B9A7', 2), ('Garden', '#D7DFAE', 3),
  ('Blue', '#B6C8D1', 4), ('Sand', '#D8D0B9', 5), ('Lavender', '#C8B5C6', 6), ('Sage', '#AFC5B5', 7)
on conflict do nothing;

insert into public.cover_images (name, image_path, image_column, sort_order) values
  ('여성 A', '/assets/cover_girl_01.png', 1, 1), ('여성 B', '/assets/cover_girl_02.png', 1, 2),
  ('여성 C', '/assets/cover_girl_03.png', 1, 3), ('여성 D', '/assets/cover_girl_04.png', 1, 4),
  ('여성 E', '/assets/cover_girl_05.png', 1, 5), ('남성 A', '/assets/cover_boy_01.png', 2, 1),
  ('남성 B', '/assets/cover_boy_02.png', 2, 2), ('남성 C', '/assets/cover_boy_03.png', 2, 3),
  ('남성 D', '/assets/cover_boy_04.png', 2, 4), ('남성 E', '/assets/cover_boy_05.png', 2, 5)
on conflict do nothing;

insert into storage.buckets (id, name, public)
values ('cover-images', 'cover-images', true)
on conflict (id) do update set public = true;

alter table public.cover_colors enable row level security;
alter table public.cover_images enable row level security;

drop policy if exists cover_colors_public_read on public.cover_colors;
create policy cover_colors_public_read on public.cover_colors for select to anon, authenticated using (is_active = true);
drop policy if exists cover_colors_admin_read on public.cover_colors;
create policy cover_colors_admin_read on public.cover_colors for select to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists cover_colors_admin_write on public.cover_colors;
create policy cover_colors_admin_write on public.cover_colors for all to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists cover_images_public_read on public.cover_images;
create policy cover_images_public_read on public.cover_images for select to anon, authenticated using (is_active = true);
drop policy if exists cover_images_admin_read on public.cover_images;
create policy cover_images_admin_read on public.cover_images for select to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
drop policy if exists cover_images_admin_write on public.cover_images;
create policy cover_images_admin_write on public.cover_images for all to authenticated using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin') with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create table if not exists public.home_reviews (
  id bigint generated by default as identity primary key,
  relationship text not null,
  author text not null,
  body text not null,
  variant text,
  is_visible boolean not null default true,
  sort_order integer not null default 1,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint home_reviews_sort_order_check check (sort_order >= 1),
  constraint home_reviews_variant_check check (variant is null or variant in ('intro'))
);

create index if not exists questions_question_group_id_idx
  on public.questions(question_group_id);

create index if not exists questions_sort_order_idx
  on public.questions(sort_order);

create index if not exists my_book_answers_my_book_id_idx on public.my_book_answers(my_book_id);
create index if not exists book_type_question_groups_book_type_id_idx on public.book_type_question_groups(book_type_id);
create index if not exists home_reviews_visibility_order_idx on public.home_reviews(is_visible, sort_order);

create table if not exists public.home_banners (
  id uuid primary key default gen_random_uuid(),
  image_path text not null,
  caption text not null default '',
  link_url text not null default '',
  position text not null check (position in ('left', 'right')),
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists home_banners_visibility_position_idx
  on public.home_banners(is_visible, position);

insert into storage.buckets (id, name, public)
values ('home-banners', 'home-banners', true)
on conflict (id) do update set public = true;

alter table public.home_banners enable row level security;

drop policy if exists home_banners_public_read on public.home_banners;
create policy home_banners_public_read on public.home_banners
  for select to anon, authenticated
  using (is_visible = true);

drop policy if exists home_banners_admin_read on public.home_banners;
create policy home_banners_admin_read on public.home_banners
  for select to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists home_banners_admin_write on public.home_banners;
create policy home_banners_admin_write on public.home_banners
  for all to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create table if not exists public.moment_authors (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  role text not null default 'author' check (role in ('author', 'admin')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moment_time_slots (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.moment_authors(id) on delete cascade,
  slot_time time not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.moment_entries (
  id bigint generated by default as identity primary key,
  slot_id bigint not null references public.moment_time_slots(id) on delete cascade,
  moment_date date not null,
  body text not null,
  is_visible boolean not null default true,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (slot_id, moment_date)
);

create index if not exists moment_entries_date_visibility_idx
  on public.moment_entries(moment_date, is_visible);
create index if not exists moment_time_slots_author_id_idx
  on public.moment_time_slots(author_id);

alter table public.question_groups enable row level security;
alter table public.questions enable row level security;
alter table public.book_types enable row level security;
alter table public.book_type_question_groups enable row level security;
alter table public.question_book_types enable row level security;
alter table public.my_books enable row level security;
alter table public.my_book_answers enable row level security;
alter table public.publications enable row level security;
alter table public.home_reviews enable row level security;
alter table public.moment_authors enable row level security;
alter table public.moment_time_slots enable row level security;
alter table public.moment_entries enable row level security;

drop policy if exists moment_authors_self_read on public.moment_authors;
create policy moment_authors_self_read on public.moment_authors
  for select to authenticated
  using (id = auth.uid() or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists moment_authors_self_write on public.moment_authors;
drop policy if exists moment_authors_admin_write on public.moment_authors;
create policy moment_authors_admin_write on public.moment_authors
  for all to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists moment_slots_owner_read on public.moment_time_slots;
create policy moment_slots_owner_read on public.moment_time_slots
  for select to authenticated
  using (author_id = auth.uid() or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists moment_slots_owner_write on public.moment_time_slots;
create policy moment_slots_owner_write on public.moment_time_slots
  for all to authenticated
  using (
    (author_id = auth.uid() and exists (select 1 from public.moment_authors authors where authors.id = auth.uid() and authors.is_active))
    or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  )
  with check (
    (author_id = auth.uid() and exists (select 1 from public.moment_authors authors where authors.id = auth.uid() and authors.is_active))
    or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
  );

drop policy if exists moment_entries_owner_read on public.moment_entries;
create policy moment_entries_owner_read on public.moment_entries
  for select to authenticated
  using (
    exists (
      select 1 from public.moment_time_slots slots
      where slots.id = slot_id
        and (
          (slots.author_id = auth.uid() and exists (select 1 from public.moment_authors authors where authors.id = auth.uid() and authors.is_active))
          or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
        )
    )
  );

drop policy if exists moment_entries_owner_write on public.moment_entries;
create policy moment_entries_owner_write on public.moment_entries
  for all to authenticated
  using (
    exists (
      select 1 from public.moment_time_slots slots
      where slots.id = slot_id
        and (
          (slots.author_id = auth.uid() and exists (select 1 from public.moment_authors authors where authors.id = auth.uid() and authors.is_active))
          or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
        )
    )
  )
  with check (
    exists (
      select 1 from public.moment_time_slots slots
      where slots.id = slot_id
        and slots.is_active
        and (
          (slots.author_id = auth.uid() and exists (select 1 from public.moment_authors authors where authors.id = auth.uid() and authors.is_active))
          or (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin'
        )
    )
  );

drop policy if exists home_reviews_public_read on public.home_reviews;
create policy home_reviews_public_read on public.home_reviews
  for select to anon, authenticated
  using (is_visible = true and (published_at is null or published_at <= now()));

drop policy if exists home_reviews_admin_read on public.home_reviews;
create policy home_reviews_admin_read on public.home_reviews
  for select to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists home_reviews_admin_write on public.home_reviews;
create policy home_reviews_admin_write on public.home_reviews
  for all to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into public.home_reviews (id, relationship, author, body, variant, is_visible, sort_order)
values
  (1, '구매자 후기', '북촌꾸러미연구소', '나의 이야기 노트를 구매하신 분들의 후기입니다. 아끼는 마음을 전할 수 있어서 좋았습니다', 'intro', true, 1),
  (2, '딸이 엄마에게', '최*진', '노트에 있는 ‘나와 부모님''질문을 엄마에게 했더니 눈을 반짝이며 할머니, 할아버지 얘기를 하시더라고요. 그 모습을 보고 많은 감정이 올라왔어요.', null, true, 2),
  (3, '아들이 엄마에게', '김*수', '용돈 드릴 때 함 드려보려고요. 쑥쓰럽기는 하지만 어머니를 마음에 두고 있다는 걸 전하고 싶거든요. 그래서 대화가 좀 늘면 좋겠어요.', null, true, 3),
  (4, '내가 나에게', '오*주', '노트를 보고 부모님에게 선물하면 좋겠다고 생각했는데, 질문들을 보니 나도 써보고 싶다는 생각이 들더라고요. 내 삶도 지금쯤 정리해보고 싶었어요.', null, true, 4),
  (5, '조카가 이모에게', '고*경', '엄마에게 선물했는데 4시간만에 쓰시고 고맙다고 전화가 왔어요. 그리고 이모들에게도 선물하면 좋겠다고 하셔서 바로 선물했어요. 친구들에게는 본인이 사서 선물하겠다고 하시더라고요.', null, true, 5),
  (6, '딸이 아빠에게', '이*희', '아빠를 취향조차 잘 모르겠더라고요. 이 노트를 통해서 아빠를 좀 더 알고 싶어요.', null, true, 6),
  (7, '후배가 선배에게', '신*우', '은퇴한 선배에게 심심할 때 끄적여 보시라고 선물하면 좋을 거 같아요.', null, true, 7)
on conflict (id) do update set
  relationship = excluded.relationship,
  author = excluded.author,
  body = excluded.body,
  variant = excluded.variant,
  is_visible = excluded.is_visible,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.question_groups (id, name, description, sort_order)
values
  (1, '어린 시절', '유년기와 성장 과정에 대한 질문 그룹', 1),
  (2, '학교생활', '학교생활과 배움에 대한 질문 그룹', 2),
  (3, '가족', '가족과 관계에 대한 질문 그룹', 3),
  (4, '친구', '친구와 추억에 대한 질문 그룹', 4),
  (5, '결혼', '결혼과 동반자에 대한 질문 그룹', 5),
  (6, '직장', '일과 커리어에 대한 질문 그룹', 6),
  (7, '부모', '부모와 자녀 관계에 대한 질문 그룹', 7),
  (8, '인생철학', '삶의 가치관과 철학에 대한 질문 그룹', 8)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.questions (
  id,
  content,
  question_group_id,
  sort_order,
  is_active,
  in_use,
  created_at,
  updated_at
)
values
  (
    1,
    '어린 시절 가장 기억나는 일은 무엇인가요?',
    1,
    1,
    true,
    true,
    '2026-07-09T00:00:00.000Z',
    '2026-07-09T00:00:00.000Z'
  ),
  (
    2,
    '학교생활 중 가장 즐거웠던 순간은 언제였나요?',
    2,
    2,
    true,
    false,
    '2026-07-09T00:00:00.000Z',
    '2026-07-09T00:00:00.000Z'
  ),
  (
    3,
    '가족에게 가장 고마웠던 기억은 무엇인가요?',
    3,
    3,
    true,
    true,
    '2026-07-09T00:00:00.000Z',
    '2026-07-09T00:00:00.000Z'
  ),
  (
    4,
    '삶에서 중요하게 지키고 싶은 원칙은 무엇인가요?',
    8,
    4,
    false,
    false,
    '2026-07-09T00:00:00.000Z',
    '2026-07-09T00:00:00.000Z'
  )
on conflict (id) do update set
  content = excluded.content,
  question_group_id = excluded.question_group_id,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  in_use = excluded.in_use,
  updated_at = excluded.updated_at;

select setval(
  pg_get_serial_sequence('public.question_groups', 'id'),
  coalesce((select max(id) from public.question_groups), 1),
  true
);

insert into public.book_types (id, name, description, cover_image)
values
  (1, '부모님 이야기', '부모님께 전하고 싶은 기억과 마음을 담는 책', 'classic'),
  (2, '나의 자서전', '나의 삶과 중요한 순간을 기록하는 책', 'archive'),
  (3, '나의 싱글 라이프', '나답게 살아온 일상을 기록하는 책', 'garden')
on conflict (id) do update set
  name = excluded.name, description = excluded.description, cover_image = excluded.cover_image, updated_at = now();

insert into public.book_type_question_groups (book_type_id, question_group_id)
values (1, 1), (1, 3), (1, 5), (1, 7), (2, 1), (2, 2), (2, 3), (2, 4), (2, 6), (2, 8), (3, 1), (3, 4), (3, 6), (3, 8)
on conflict do nothing;

insert into public.question_book_types (question_id, book_type_id)
select q.id, b.id
from public.questions q cross join public.book_types b
where not exists (select 1 from public.question_book_types);

select setval(pg_get_serial_sequence('public.book_types', 'id'), coalesce((select max(id) from public.book_types), 1), true);

select setval(
  pg_get_serial_sequence('public.questions', 'id'),
  coalesce((select max(id) from public.questions), 1),
  true
);
