-- 표지 관리 기능 전용 migration
-- 기존 사용자/책 데이터는 변경하지 않습니다.

create table if not exists public.cover_colors (
  id bigint generated by default as identity primary key,
  name text not null,
  color_value text not null check (color_value ~ '^#[0-9A-Fa-f]{6}$'),
  sort_order integer not null default 1 check (sort_order >= 1),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.cover_images (
  id bigint generated by default as identity primary key,
  name text not null,
  image_path text not null,
  image_column integer not null default 1 check (image_column in (1, 2)),
  sort_order integer not null default 1 check (sort_order >= 1),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cover_colors_active_order_idx
  on public.cover_colors(is_active, sort_order);

create index if not exists cover_images_active_column_order_idx
  on public.cover_images(is_active, image_column, sort_order);

create unique index if not exists cover_colors_name_value_uidx
  on public.cover_colors(name, color_value);

create unique index if not exists cover_images_name_path_column_uidx
  on public.cover_images(name, image_path, image_column);

insert into public.cover_colors (name, color_value, sort_order)
values
  ('Cream', '#C5A58E', 1),
  ('Rose', '#D9B9A7', 2),
  ('Garden', '#D7DFAE', 3),
  ('Blue', '#B6C8D1', 4),
  ('Sand', '#D8D0B9', 5),
  ('Lavender', '#C8B5C6', 6),
  ('Sage', '#AFC5B5', 7)
on conflict (name, color_value) do nothing;

insert into public.cover_images (name, image_path, image_column, sort_order)
values
  ('여성 A', '/assets/cover_girl_01.png', 1, 1),
  ('여성 B', '/assets/cover_girl_02.png', 1, 2),
  ('여성 C', '/assets/cover_girl_03.png', 1, 3),
  ('여성 D', '/assets/cover_girl_04.png', 1, 4),
  ('여성 E', '/assets/cover_girl_05.png', 1, 5),
  ('남성 A', '/assets/cover_boy_01.png', 2, 1),
  ('남성 B', '/assets/cover_boy_02.png', 2, 2),
  ('남성 C', '/assets/cover_boy_03.png', 2, 3),
  ('남성 D', '/assets/cover_boy_04.png', 2, 4),
  ('남성 E', '/assets/cover_boy_05.png', 2, 5)
on conflict (name, image_path, image_column) do nothing;

alter table public.cover_colors enable row level security;
alter table public.cover_images enable row level security;

drop policy if exists cover_colors_public_read on public.cover_colors;
create policy cover_colors_public_read on public.cover_colors
  for select to anon, authenticated using (is_active = true);

drop policy if exists cover_images_public_read on public.cover_images;
create policy cover_images_public_read on public.cover_images
  for select to anon, authenticated using (is_active = true);

insert into storage.buckets (id, name, public)
values ('cover-images', 'cover-images', true)
on conflict (id) do update set public = true;

drop policy if exists cover_images_storage_public_read on storage.objects;
create policy cover_images_storage_public_read on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'cover-images');
