-- 전달 방식은 선물 자체의 최초 방식과 별도 활동 이력으로 분리한다.
alter table public.gifts add column if not exists initial_delivery_method text;
alter table public.gifts drop constraint if exists gifts_initial_delivery_method_check;
alter table public.gifts add constraint gifts_initial_delivery_method_check
  check (initial_delivery_method is null or initial_delivery_method in ('kakao', 'email', 'code'));

create table if not exists public.gift_deliveries (
  id bigint generated by default as identity primary key,
  gift_id bigint not null references public.gifts(id) on delete cascade,
  method text not null check (method in ('kakao', 'email', 'code')),
  created_at timestamptz not null default now(),
  metadata jsonb
);

create index if not exists gift_deliveries_gift_id_created_at_idx
  on public.gift_deliveries(gift_id, created_at);

alter table public.gift_deliveries enable row level security;
