create table if not exists public.question_variations (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  book_type_id bigint not null references public.book_types(id) on delete cascade,
  text text not null default '',
  sort_order integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (question_id, book_type_id)
);

create index if not exists question_variations_question_id_idx on public.question_variations(question_id);
create index if not exists question_variations_book_type_id_idx on public.question_variations(book_type_id);
