-- Share URLs use a separate token and never expose the gift code.
create table if not exists public.gift_share_tokens (
  id bigint generated by default as identity primary key,
  gift_id bigint not null references public.gifts(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create index if not exists gift_share_tokens_gift_id_idx
  on public.gift_share_tokens(gift_id);
create index if not exists gift_share_tokens_active_idx
  on public.gift_share_tokens(token_hash)
  where revoked_at is null;

alter table public.gift_share_tokens enable row level security;

drop policy if exists gift_share_tokens_sender_read on public.gift_share_tokens;
create policy gift_share_tokens_sender_read on public.gift_share_tokens
  for select to authenticated
  using (exists (
    select 1 from public.gifts
    where gifts.id = gift_id
      and gifts.sender_user_id = auth.uid()
  ));

drop policy if exists gift_share_tokens_sender_write on public.gift_share_tokens;
create policy gift_share_tokens_sender_write on public.gift_share_tokens
  for all to authenticated
  using (exists (
    select 1 from public.gifts
    where gifts.id = gift_id
      and gifts.sender_user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.gifts
    where gifts.id = gift_id
      and gifts.sender_user_id = auth.uid()
  ));
