-- 선물코드 접근 기반
-- 이 migration은 선물코드 원문과 session token을 저장하지 않습니다.

create table if not exists public.gifts (
  id bigint generated by default as identity primary key,
  book_id bigint not null unique references public.my_books(id) on delete cascade,
  sender_user_id uuid references auth.users(id) on delete set null,
  sender_email text,
  status text not null default 'active' check (status in ('active', 'inactive', 'revoked')),
  gift_code_hash text not null unique,
  code_version integer not null default 1 check (code_version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_accessed_at timestamptz,
  code_issued_at timestamptz not null default now(),
  revoked_at timestamptz
);

create index if not exists gifts_status_idx on public.gifts(status);
create index if not exists gifts_sender_user_id_idx on public.gifts(sender_user_id);
create index if not exists gifts_last_accessed_at_idx on public.gifts(last_accessed_at);

create table if not exists public.gift_sessions (
  id uuid primary key default gen_random_uuid(),
  gift_id bigint not null references public.gifts(id) on delete cascade,
  session_token_hash text not null unique,
  created_at timestamptz not null default now(),
  last_accessed_at timestamptz not null default now(),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  user_agent text
);

create index if not exists gift_sessions_gift_id_idx on public.gift_sessions(gift_id);
create index if not exists gift_sessions_active_expiry_idx on public.gift_sessions(expires_at)
  where revoked_at is null;

alter table public.gifts enable row level security;
alter table public.gift_sessions enable row level security;
